fix(garmin-express): use correct SHA256 hash of installer
At the moment, the installation of `v7.28.0` fails with:
```shell
ERROR: Checksum for 'D:\Development\PackageCaches\Chocolatey\garmin-express\7.28.0\GarminExpress.exe' did not meet 'f48f621133d5b158963e6048d521f881fa152d1f598b748bdaa229126a89352c' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The upgrade of garmin-express was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\garmin-express\tools\chocolateyInstall.ps1'.
 See log for details.
```